### PR TITLE
latest version of my projects

### PR DESCRIPTION
**Pull request by snowsandpatrol**

### CODE REVIEW

**Comment by gabrielle-ong** [comment]
Hi Limin, we can't accept your pull request because you are adding your project files in addition to your read me. Please save your files somewhere else on your local (instead of this repo), remove them from this repo, push the changes to your remote and resubmit a pull request. If you need help to find us tmr:)

**Comment by snowsandpatrol** [comment]
pushed read only file, only.

**Comment by gabrielle-ong** [comment]
Hey Limin, you're changing 2 files. please edit only your readme, commit again and resubmit a pull request. Thanks!

**Comment by snowsandpatrol** [comment]
hi please accept this new pull request - changes in readme file.

**Pull request closed without merging**
